spring:
    profiles:
        active:
            dev
---
server:
    port: 8888
spring:
    profiles: dev
    application:
        name: microservicecloud-config-client-dev
eureka:
    client:
        service-url:
            defaultZone: http://localhost:7001/eureka/
---
server:
    port: 9999
spring:
    profiles: test
    application:
        name: microservicecloud-config-client-test
eureka:
    client:
        service-url:
            defaultZone: http://localhost:7001/eureka/