spring:
    profiles:
        active:
            dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-atguigu-guo-dev
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-atguigu-guo-test