server:
  port: 8002
spring:
  application:
    name: springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud-2?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location:  classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.example.springcloud.entity
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: provider-8002
    prefer-ip-address: true
info:
  app.name: yangyang-microservicecloud-provider-8001
  company.name: www.yangyang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$