server:
  port: 80

spring:
  application:
    name: springcloud-consumer-test

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: consumer-80
info:
  app.name: yangyang-microservicecloud-consumer-80
  company.name: www.yangyang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$