server:
  port: 6001
spring:
  application:
    name: consumer-6001-feign

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
  instance:
    instance-id: consumer-feign
    prefer-ip-address: true
info:
  app.name: yangyang-microservicecloud-consumer-6001-feign
  company.name: www.yangyang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$